sudo: required
dist: trusty

language: python
# well its really octave, but that is not supported

matrix:
  include:
    - python: "2.7"
      env: PYTAVE=yes SYMPY_VER=1.0 OCT_PPA=no BUILD_OCT=yes DOCTEST=yes COLUMNS=80

# need octave devel pkgs for doctest (has compiled code as of July 2015)
install:
  - if [ "x$OCT_PPA" = "xyes" ]; then
        sudo apt-add-repository -y ppa:octave/stable;
        sudo apt-get update -qq -y;
        sudo apt-get install -qq -y octave liboctave-dev;
    fi
  - if [ "x$BUILD_OCT" = "xyes" ]; then
        hg clone http://www.octave.org/hg/octave;
        cd octave;
        hg -v pull;
        hg -v update;
        ./bootstrap;
        mkdir build_;
        cd build_;
        sudo apt-get install -qq -y g++ gcc gfortran make autoconf automake bison flex gperf gzip icoutils librsvg2-bin libtool perl rsync tar;
        sudo apt-get install -qq -y libblas-dev liblapack-dev libpcre3-dev libarpack2-dev libcurl4-gnutls-dev epstool libfftw3-dev transfig libfltk1.3-dev libfontconfig1-dev libfreetype6-dev libgl2ps-dev libglpk-dev libreadline-dev gnuplot libgraphicsmagick++-dev libhdf5-serial-dev openjdk-7-jdk libsndfile1-dev llvm-dev lpr texinfo libgl1-mesa-dev libosmesa6-dev pstoedit portaudio19-dev libqhull-dev libqrupdate-dev libqscintilla2-dev libqt4-dev libqtcore4 libqtwebkit4 libqt4-network libqtgui4 libsuitesparse-dev libxft-dev zlib1g-dev;
        ../configure --prefix=/opt/octave_dev;
        make;
        make check;
        sudo make install;
    fi
  - "pip install sympy==$SYMPY_VER"
  - if [ "x$DOCTEST" = "xyes" ]; then
        octave -W --no-gui --eval "pkg install -forge doctest";
    fi
  - if [ "x$PYTAVE" = "xyes" ]; then
        sudo apt-get install -qq -y libboost-python-dev;
        hg clone https://bitbucket.org/genuinelucifer/pytave_main;
        cd pytave_main;
        pwd;
        autoreconf --install;
        ./configure --with-octave=/opt/octave_dev;
        make;
        sudo make install;
        cd ..;
    fi


# all commands here must have exit code 0 for the build to be called "passing"
# debugging: octave -W --no-gui --eval "syms x; A = [x sin(x) x^3]; A; exit(0)"
script:
  - octave -W --no-gui --eval "ver; pwd; exit(0)"
  - stty cols 80 rows 40
  - tput cols; stty size
  - pushd src; make; popd
  - pushd inst
  - octave --path=/home/travis/build/cbm755/octsympy/pytave_main -W --no-gui --eval "r = octsympy_tests; exit(r)"
  - cat octsympy_tests.log
  - if [ "x$DOCTEST" = "xyes" ]; then
        octave --path=/home/travis/build/cbm755/octsympy/pytave_main -W --no-gui --eval "pkg load doctest; syms x; r = doctest('.'); exit(~r)";
    fi
  - popd

#after_script:
#  - echo ${TRAVIS_TEST_RESULT}
