language: python
# well its really octave, but that is not supported

matrix:
  include:
    - python: "2.7"
      env: SYMPY_VER=0.7.6 DOCTEST=yes COLUMNS=80
    - python: "3.4"
      env: SYMPY_VER=0.7.6.1 DOCTEST=yes COLUMNS=80

# need octave devel pkgs for doctest (has compiled code as of July 2015)
# TODO: once doctest is in OF, change to "install -forge" below
install:
  - sudo apt-add-repository --yes ppa:octave/stable
  - sudo apt-get update
  - sudo apt-get install octave liboctave-dev
  - "pip install sympy==$SYMPY_VER"
  - #if [ "x$DOCTEST" = "xyes" ]; then
    #    octave -W --eval "pkg install -forge doctest";
    #fi
  - # Or for a specific doctest version:
    if [ "x$DOCTEST" = "xyes" ]; then
        wget https://github.com/catch22/octave-doctest/releases/download/v0.4.1/doctest-0.4.1.tar.gz;
        octave -W --eval "pkg install doctest-0.4.1.tar.gz";
    fi

# all commands here must have exit code 0 for the build to be called "passing"
# debugging: octave -W --eval "syms x; A = [x sin(x) x^3]; A; exit(0)"
script:
  - octave -W --eval "ver; pwd; exit(0)"
  - tput cols; stty size
  - pushd src; make; popd
  - pushd inst
  - octave -W --eval "r = octsympy_tests; exit(r)"
  - cat octsympy_tests.log
  - if [ "x$DOCTEST" = "xyes" ]; then
        octave -W --eval "pkg load doctest; syms x; r = doctest('.'); exit(~r)";
    fi
  - popd

#after_script:
#  - echo ${TRAVIS_TEST_RESULT}
